name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          check-latest: true
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Build rules
        run: yarn build
      - name: Eslint check
        run: yarn lint

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24, 26]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Cache dprint
        id: cache-dprint
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: node_modules/.cache/dprint
          key: ${{ runner.os }}-dprint-${{ hashFiles('packages/dprint-config/lib/recommended.json', 'packages/dprint-config/package.json') }}
      - name: Build rules
        run: yarn build
      - name: Test
        run: yarn test
        env:
          DPRINT_CACHE_DIR: ${{ github.workspace }}/node_modules/.cache/dprint
